<?php

return [
  'icommerce.tags' => [
    'manage' => 'icommerce::tags.manage resource',
    'index' => 'icommerce::tags.list resource',
    'create' => 'icommerce::tags.create resource',
    'edit' => 'icommerce::tags.edit resource',
    'destroy' => 'icommerce::tags.destroy resource',
  ],
  'icommerce.categories' => [
    'manage' => 'icommerce::categories.manage resource',
    'index' => 'icommerce::categories.list resource',
    'create' => 'icommerce::categories.create resource',
    'edit' => 'icommerce::categories.edit resource',
    'destroy' => 'icommerce::categories.destroy resource',
  ],
  'icommerce.manufacturers' => [
    'manage' => 'icommerce::manufacturers.manage resource',
    'index' => 'icommerce::manufacturers.list resource',
    'create' => 'icommerce::manufacturers.create resource',
    'edit' => 'icommerce::manufacturers.edit resource',
    'destroy' => 'icommerce::manufacturers.destroy resource',
  ],
  'icommerce.products' => [
    'manage' => 'icommerce::products.manage resource',
    'index' => 'icommerce::products.list resource',
    'create' => 'icommerce::products.create resource',
    'edit' => 'icommerce::products.edit resource',
    'destroy' => 'icommerce::products.destroy resource',
    'import' => 'icommerce::products.import resource',
    'rating' => 'icommerce::products.rating resource',
  ],
  'icommerce.bulkload' => [
    'manage' => 'icommerce::bulkload.manage',
    'import' => 'icommerce::bulkload.import',
    'export' => 'icommerce::bulkload.export',
  ],
  'icommerce.producttags' => [
    'manage' => 'icommerce::producttags.manage resource',
    'index' => 'icommerce::producttags.list resource',
    'create' => 'icommerce::producttags.create resource',
    'edit' => 'icommerce::producttags.edit resource',
    'destroy' => 'icommerce::producttags.destroy resource',
  ],
  'icommerce.productcategories' => [
    'manage' => 'icommerce::productcategories.manage resource',
    'index' => 'icommerce::productcategories.list resource',
    'create' => 'icommerce::productcategories.create resource',
    'edit' => 'icommerce::productcategories.edit resource',
    'destroy' => 'icommerce::productcategories.destroy resource',
  ],
  'icommerce.options' => [
    'manage' => 'icommerce::options.manage resource',
    'index' => 'icommerce::options.list resource',
    'create' => 'icommerce::options.create resource',
    'edit' => 'icommerce::options.edit resource',
    'destroy' => 'icommerce::options.destroy resource',
  ],
  'icommerce.coupons' => [
    'manage' => 'icommerce::coupons.manage resource',
    'manage' => 'icommerce::coupons.manage resource',
    'index' => 'icommerce::coupons.list resource',
    'create' => 'icommerce::coupons.create resource',
    'edit' => 'icommerce::coupons.edit resource',
    'destroy' => 'icommerce::coupons.destroy resource',
  ],
  'icommerce.shippingcouriers' => [
    'manage' => 'icommerce::shippingcouriers.manage resource',
    'index' => 'icommerce::shippingcouriers.list resource',
    'create' => 'icommerce::shippingcouriers.create resource',
    'edit' => 'icommerce::shippingcouriers.edit resource',
    'destroy' => 'icommerce::shippingcouriers.destroy resource',
  ],
  'icommerce.currencies' => [
    'manage' => 'icommerce::currencies.manage resource',
    'index' => 'icommerce::currencies.list resource',
    'create' => 'icommerce::currencies.create resource',
    'edit' => 'icommerce::currencies.edit resource',
    'destroy' => 'icommerce::currencies.destroy resource',
  ],
  'icommerce.orders' => [
    'manage' => 'icommerce::orders.manage resource',
    'index' => 'icommerce::orders.list resource',
    'index-all' => 'icommerce::orders.list-all resource',
    'show' => 'icommerce::orders.show resource',
    'show-others' => 'icommerce::orders.show-others resource',
    'create' => 'icommerce::orders.create resource',
    'edit' => 'icommerce::orders.edit resource',
    'destroy' => 'icommerce::orders.destroy resource',
  ],
  'icommerce.orderstatus' => [
    'manage' => 'icommerce::orderstatus.manage resource',
    'index' => 'icommerce::orderstatus.list resource',
    'create' => 'icommerce::orderstatus.create resource',
    'edit' => 'icommerce::orderstatus.edit resource',
    'destroy' => 'icommerce::orderstatus.destroy resource',
  ],
  'icommerce.productdiscounts' => [
    'manage' => 'icommerce::productdiscounts.manage resource',
    'index' => 'icommerce::productdiscounts.list resource',
    'create' => 'icommerce::productdiscounts.create resource',
    'edit' => 'icommerce::productdiscounts.edit resource',
    'destroy' => 'icommerce::productdiscounts.destroy resource',
  ],
  'icommerce.optionvalues' => [
    'manage' => 'icommerce::optionvalues.manage resource',
    'index' => 'icommerce::optionvalues.list resource',
    'create' => 'icommerce::optionvalues.create resource',
    'edit' => 'icommerce::optionvalues.edit resource',
    'destroy' => 'icommerce::optionvalues.destroy resource',
  ],
  'icommerce.productoptions' => [
    'manage' => 'icommerce::productoptions.manage resource',
    'index' => 'icommerce::productoptions.list resource',
    'create' => 'icommerce::productoptions.create resource',
    'edit' => 'icommerce::productoptions.edit resource',
    'destroy' => 'icommerce::productoptions.destroy resource',
  ],
  'icommerce.productoptionvalues' => [
    'manage' => 'icommerce::productoptionvalues.manage resource',
    'index' => 'icommerce::productoptionvalues.list resource',
    'create' => 'icommerce::productoptionvalues.create resource',
    'edit' => 'icommerce::productoptionvalues.edit resource',
    'destroy' => 'icommerce::productoptionvalues.destroy resource',
  ],
  'icommerce.orderproducts' => [
    'manage' => 'icommerce::orderproducts.manage resource',
    'index' => 'icommerce::orderproducts.list resource',
    'create' => 'icommerce::orderproducts.create resource',
    'edit' => 'icommerce::orderproducts.edit resource',
    'destroy' => 'icommerce::orderproducts.destroy resource',
  ],
  'icommerce.orderoptions' => [
    'manage' => 'icommerce::orderoptions.manage resource',
    'index' => 'icommerce::orderoptions.list resource',
    'create' => 'icommerce::orderoptions.create resource',
    'edit' => 'icommerce::orderoptions.edit resource',
    'destroy' => 'icommerce::orderoptions.destroy resource',
  ],
  'icommerce.orderhistories' => [
    'manage' => 'icommerce::orderhistories.manage resource',
    'index' => 'icommerce::orderhistories.list resource',
    'create' => 'icommerce::orderhistories.create resource',
    'edit' => 'icommerce::orderhistories.edit resource',
    'destroy' => 'icommerce::orderhistories.destroy resource',
  ],
  'icommerce.ordershipments' => [
    'manage' => 'icommerce::ordershipments.manage resource',
    'index' => 'icommerce::ordershipments.list resource',
    'create' => 'icommerce::ordershipments.create resource',
    'edit' => 'icommerce::ordershipments.edit resource',
    'destroy' => 'icommerce::ordershipments.destroy resource',
  ],
  'icommerce.couponcategories' => [
    'manage' => 'icommerce::couponcategories.manage resource',
    'index' => 'icommerce::couponcategories.list resource',
    'create' => 'icommerce::couponcategories.create resource',
    'edit' => 'icommerce::couponcategories.edit resource',
    'destroy' => 'icommerce::couponcategories.destroy resource',
  ],
  'icommerce.couponproducts' => [
    'manage' => 'icommerce::couponproducts.manage resource',
    'index' => 'icommerce::couponproducts.list resource',
    'create' => 'icommerce::couponproducts.create resource',
    'edit' => 'icommerce::couponproducts.edit resource',
    'destroy' => 'icommerce::couponproducts.destroy resource',
  ],
  'icommerce.couponhistories' => [
    'manage' => 'icommerce::couponhistories.manage resource',
    'index' => 'icommerce::couponhistories.list resource',
    'create' => 'icommerce::couponhistories.create resource',
    'edit' => 'icommerce::couponhistories.edit resource',
    'destroy' => 'icommerce::couponhistories.destroy resource',
  ],
  'icommerce.payments' => [
    'manage' => 'icommerce::payments.manage resource',
    'index' => 'icommerce::payments.list resource',
    'create' => 'icommerce::payments.create resource',
    'edit' => 'icommerce::payments.edit resource',
    'destroy' => 'icommerce::payments.destroy resource',
  ],
  'icommerce.shippings' => [
    'manage' => 'icommerce::shippings.manage resource',
    'index' => 'icommerce::shippings.list resource',
    'create' => 'icommerce::shippings.create resource',
    'edit' => 'icommerce::shippings.edit resource',
    'destroy' => 'icommerce::shippings.destroy resource',
  ],
  'icommerce.taxrates' => [
    'manage' => 'icommerce::taxrates.manage resource',
    'index' => 'icommerce::taxrates.list resource',
    'create' => 'icommerce::taxrates.create resource',
    'edit' => 'icommerce::taxrates.edit resource',
    'destroy' => 'icommerce::taxrates.destroy resource',
  ],
  'icommerce.taxclasses' => [
    'manage' => 'icommerce::taxclasses.manage resource',
    'index' => 'icommerce::taxclasses.list resource',
    'create' => 'icommerce::taxclasses.create resource',
    'edit' => 'icommerce::taxclasses.edit resource',
    'destroy' => 'icommerce::taxclasses.destroy resource',
  ],
  'icommerce.taxclassrates' => [
    'manage' => 'icommerce::taxclassrates.manage resource',
    'index' => 'icommerce::taxclassrates.list resource',
    'create' => 'icommerce::taxclassrates.create resource',
    'edit' => 'icommerce::taxclassrates.edit resource',
    'destroy' => 'icommerce::taxclassrates.destroy resource',
  ],
  'icommerce.itemtypes' => [
    'manage' => 'icommerce::itemtypes.manage resource',
    'index' => 'icommerce::itemtypes.list resource',
    'create' => 'icommerce::itemtypes.create resource',
    'edit' => 'icommerce::itemtypes.edit resource',
    'destroy' => 'icommerce::itemtypes.destroy resource',
  ],
  'icommerce.relatedproducts' => [
    'manage' => 'icommerce::relatedproducts.manage resource',
    'index' => 'icommerce::relatedproducts.list resource',
    'create' => 'icommerce::relatedproducts.create resource',
    'edit' => 'icommerce::relatedproducts.edit resource',
    'destroy' => 'icommerce::relatedproducts.destroy resource',
  ],
  
  'icommerce.payment-methods' => [
    'manage' => 'icommerce::paymentmethods.manage resource',
    'index' => 'icommerce::paymentmethods.list resource',
    'create' => 'icommerce::paymentmethods.create resource',
    'edit' => 'icommerce::paymentmethods.edit resource',
    'destroy' => 'icommerce::paymentmethods.destroy resource',
  ],
  
  'icommerce.cart' => [
    'manage' => 'icommerce::cart.manage resource',
    'index' => 'icommerce::cart.list resource',
    'create' => 'icommerce::cart.create resource',
    'edit' => 'icommerce::cart.edit resource',
    'destroy' => 'icommerce::cart.destroy resource',
  ],
  'icommerce.cartproductoptions' => [
    'manage' => 'icommerce::cartproductoptions.manage resource',
    'index' => 'icommerce::cartproductoptions.list resource',
    'create' => 'icommerce::cartproductoptions.create resource',
    'edit' => 'icommerce::cartproductoptions.edit resource',
    'destroy' => 'icommerce::cartproductoptions.destroy resource',
  ],
  'icommerce.shipping-methods' => [
    'manage' => 'icommerce::shippingmethods.manage resource',
    'index' => 'icommerce::shippingmethods.list resource',
    'create' => 'icommerce::shippingmethods.create resource',
    'edit' => 'icommerce::shippingmethods.edit resource',
    'destroy' => 'icommerce::shippingmethods.destroy resource',
  ],
  'icommerce.shippingmethodgeozones' => [
    'manage' => 'icommerce::shippingmethodgeozones.manage resource',
    'index' => 'icommerce::shippingmethodgeozones.list resource',
    'create' => 'icommerce::shippingmethodgeozones.create resource',
    'edit' => 'icommerce::shippingmethodgeozones.edit resource',
    'destroy' => 'icommerce::shippingmethodgeozones.destroy resource',
  ],
  'icommerce.paymentmethodgeozones' => [
    'manage' => 'icommerce::paymentmethodgeozones.manage resource',
    'index' => 'icommerce::paymentmethodgeozones.list resource',
    'create' => 'icommerce::paymentmethodgeozones.create resource',
    'edit' => 'icommerce::paymentmethodgeozones.edit resource',
    'destroy' => 'icommerce::paymentmethodgeozones.destroy resource',
  ],
  'icommerce.quotes' => [
    'manage' => 'icommerce::quotes.manage resource',
    'index' => 'icommerce::quotes.list resource',
    'create' => 'icommerce::quotes.create resource',
    'edit' => 'icommerce::quotes.edit resource',
    'destroy' => 'icommerce::quotes.destroy resource',
  ],
// append


];
