<?php

return [
  'icommerce.categories' => [
    'manage' => 'icommerce::categories.manage resource',
    'index' => 'icommerce::categories.list resource',
    'create' => 'icommerce::categories.create resource',
    'edit' => 'icommerce::categories.edit resource',
    'destroy' => 'icommerce::categories.destroy resource',
    'restore' => 'icommerce::categories.restore resource',
  ],
  'icommerce.manufacturers' => [
    'manage' => 'icommerce::manufacturers.manage resource',
    'index' => 'icommerce::manufacturers.list resource',
    'create' => 'icommerce::manufacturers.create resource',
    'edit' => 'icommerce::manufacturers.edit resource',
    'destroy' => 'icommerce::manufacturers.destroy resource',
    'restore' => 'icommerce::manufacturers.restore resource',
  ],
  'icommerce.taxrates' => [
    'manage' => 'icommerce::taxrates.manage resource',
    'index' => 'icommerce::taxrates.list resource',
    'create' => 'icommerce::taxrates.create resource',
    'edit' => 'icommerce::taxrates.edit resource',
    'destroy' => 'icommerce::taxrates.destroy resource',
    'restore' => 'icommerce::taxrates.restore resource',
  ],
  'icommerce.taxclasses' => [
    'manage' => 'icommerce::taxclasses.manage resource',
    'index' => 'icommerce::taxclasses.list resource',
    'create' => 'icommerce::taxclasses.create resource',
    'edit' => 'icommerce::taxclasses.edit resource',
    'destroy' => 'icommerce::taxclasses.destroy resource',
    'restore' => 'icommerce::taxclasses.restore resource',
  ],
  'icommerce.taxclassrates' => [
    'manage' => 'icommerce::taxclassrates.manage resource',
    'index' => 'icommerce::taxclassrates.list resource',
    'create' => 'icommerce::taxclassrates.create resource',
    'edit' => 'icommerce::taxclassrates.edit resource',
    'destroy' => 'icommerce::taxclassrates.destroy resource',
    'restore' => 'icommerce::taxclassrates.restore resource',
  ],
  'icommerce.products' => [
    'manage' => 'icommerce::products.manage resource',
    'index' => 'icommerce::products.list resource',
    'create' => 'icommerce::products.create resource',
    'edit' => 'icommerce::products.edit resource',
    'destroy' => 'icommerce::products.destroy resource',
    'restore' => 'icommerce::products.restore resource',
  ],
  'icommerce.productcategories' => [
    'manage' => 'icommerce::productcategories.manage resource',
    'index' => 'icommerce::productcategories.list resource',
    'create' => 'icommerce::productcategories.create resource',
    'edit' => 'icommerce::productcategories.edit resource',
    'destroy' => 'icommerce::productcategories.destroy resource',
    'restore' => 'icommerce::productcategories.restore resource',
  ],
  'icommerce.options' => [
    'manage' => 'icommerce::options.manage resource',
    'index' => 'icommerce::options.list resource',
    'create' => 'icommerce::options.create resource',
    'edit' => 'icommerce::options.edit resource',
    'destroy' => 'icommerce::options.destroy resource',
    'restore' => 'icommerce::options.restore resource',
  ],
  'icommerce.coupons' => [
    'manage' => 'icommerce::coupons.manage resource',
    'index' => 'icommerce::coupons.list resource',
    'create' => 'icommerce::coupons.create resource',
    'edit' => 'icommerce::coupons.edit resource',
    'destroy' => 'icommerce::coupons.destroy resource',
    'restore' => 'icommerce::coupons.restore resource',
  ],
  'icommerce.currencies' => [
    'manage' => 'icommerce::currencies.manage resource',
    'index' => 'icommerce::currencies.list resource',
    'create' => 'icommerce::currencies.create resource',
    'edit' => 'icommerce::currencies.edit resource',
    'destroy' => 'icommerce::currencies.destroy resource',
    'restore' => 'icommerce::currencies.restore resource',
  ],
  'icommerce.orderstatuses' => [
    'manage' => 'icommerce::orderstatuses.manage resource',
    'index' => 'icommerce::orderstatuses.list resource',
    'create' => 'icommerce::orderstatuses.create resource',
    'edit' => 'icommerce::orderstatuses.edit resource',
    'destroy' => 'icommerce::orderstatuses.destroy resource',
    'restore' => 'icommerce::orderstatuses.restore resource',
  ],
  'icommerce.orders' => [
    'manage' => 'icommerce::orders.manage resource',
    'index' => 'icommerce::orders.list resource',
    'index-all' => 'icommerce::orders.list-all resource',
    'show' => 'icommerce::orders.show resource',
    'show-others' => 'icommerce::orders.show-others resource',
    'create' => 'icommerce::orders.create resource',
    'edit' => 'icommerce::orders.edit resource',
    'destroy' => 'icommerce::orders.destroy resource',
    'restore' => 'icommerce::orders.restore resource',
  ],
  'icommerce.optionvalues' => [
    'manage' => 'icommerce::optionvalues.manage resource',
    'index' => 'icommerce::optionvalues.list resource',
    'create' => 'icommerce::optionvalues.create resource',
    'edit' => 'icommerce::optionvalues.edit resource',
    'destroy' => 'icommerce::optionvalues.destroy resource',
    'restore' => 'icommerce::optionvalues.restore resource',
  ],
  'icommerce.productoptions' => [
    'manage' => 'icommerce::productoptions.manage resource',
    'index' => 'icommerce::productoptions.list resource',
    'create' => 'icommerce::productoptions.create resource',
    'edit' => 'icommerce::productoptions.edit resource',
    'destroy' => 'icommerce::productoptions.destroy resource',
    'restore' => 'icommerce::productoptions.restore resource',
  ],
  'icommerce.productdiscounts' => [
    'manage' => 'icommerce::productdiscounts.manage resource',
    'index' => 'icommerce::productdiscounts.list resource',
    'create' => 'icommerce::productdiscounts.create resource',
    'edit' => 'icommerce::productdiscounts.edit resource',
    'destroy' => 'icommerce::productdiscounts.destroy resource',
    'restore' => 'icommerce::productdiscounts.restore resource',
  ],
  'icommerce.itemtypes' => [
    'manage' => 'icommerce::itemtypes.manage resource',
    'index' => 'icommerce::itemtypes.list resource',
    'create' => 'icommerce::itemtypes.create resource',
    'edit' => 'icommerce::itemtypes.edit resource',
    'destroy' => 'icommerce::itemtypes.destroy resource',
    'restore' => 'icommerce::itemtypes.restore resource',
  ],
  'icommerce.orderitems' => [
    'manage' => 'icommerce::orderitems.manage resource',
    'index' => 'icommerce::orderitems.list resource',
    'create' => 'icommerce::orderitems.create resource',
    'edit' => 'icommerce::orderitems.edit resource',
    'destroy' => 'icommerce::orderitems.destroy resource',
    'restore' => 'icommerce::orderitems.restore resource',
  ],
  'icommerce.orderoptions' => [
    'manage' => 'icommerce::orderoptions.manage resource',
    'index' => 'icommerce::orderoptions.list resource',
    'create' => 'icommerce::orderoptions.create resource',
    'edit' => 'icommerce::orderoptions.edit resource',
    'destroy' => 'icommerce::orderoptions.destroy resource',
    'restore' => 'icommerce::orderoptions.restore resource',
  ],
  'icommerce.orderstatushistories' => [
    'manage' => 'icommerce::orderstatushistories.manage resource',
    'index' => 'icommerce::orderstatushistories.list resource',
    'create' => 'icommerce::orderstatushistories.create resource',
    'edit' => 'icommerce::orderstatushistories.edit resource',
    'destroy' => 'icommerce::orderstatushistories.destroy resource',
    'restore' => 'icommerce::orderstatushistories.restore resource',
  ],
  'icommerce.couponorderhistories' => [
    'manage' => 'icommerce::couponorderhistories.manage resource',
    'index' => 'icommerce::couponorderhistories.list resource',
    'create' => 'icommerce::couponorderhistories.create resource',
    'edit' => 'icommerce::couponorderhistories.edit resource',
    'destroy' => 'icommerce::couponorderhistories.destroy resource',
    'restore' => 'icommerce::couponorderhistories.restore resource',
  ],
  'icommerce.payment-methods' => [
    'manage' => 'icommerce::paymentmethods.manage resource',
    'index' => 'icommerce::paymentmethods.list resource',
    'create' => 'icommerce::paymentmethods.create resource',
    'edit' => 'icommerce::paymentmethods.edit resource',
    'destroy' => 'icommerce::paymentmethods.destroy resource',
    'restore' => 'icommerce::paymentmethods.restore resource',
  ],
  'icommerce.transactions' => [
    'manage' => 'icommerce::transactions.manage resource',
    'index' => 'icommerce::transactions.list resource',
    'create' => 'icommerce::transactions.create resource',
    'edit' => 'icommerce::transactions.edit resource',
    'destroy' => 'icommerce::transactions.destroy resource',
    'restore' => 'icommerce::transactions.restore resource',
  ],
  'icommerce.carts' => [
    'manage' => 'icommerce::carts.manage resource',
    'index' => 'icommerce::carts.list resource',
    'create' => 'icommerce::carts.create resource',
    'edit' => 'icommerce::carts.edit resource',
    'destroy' => 'icommerce::carts.destroy resource',
    'restore' => 'icommerce::carts.restore resource',
  ],
  'icommerce.cartproducts' => [
    'manage' => 'icommerce::cartproducts.manage resource',
    'index' => 'icommerce::cartproducts.list resource',
    'create' => 'icommerce::cartproducts.create resource',
    'edit' => 'icommerce::cartproducts.edit resource',
    'destroy' => 'icommerce::cartproducts.destroy resource',
    'restore' => 'icommerce::cartproducts.restore resource',
  ],
  'icommerce.relatedproducts' => [
    'manage' => 'icommerce::relatedproducts.manage resource',
    'index' => 'icommerce::relatedproducts.list resource',
    'create' => 'icommerce::relatedproducts.create resource',
    'edit' => 'icommerce::relatedproducts.edit resource',
    'destroy' => 'icommerce::relatedproducts.destroy resource',
    'restore' => 'icommerce::relatedproducts.restore resource',
  ],
  'icommerce.cartproductoptions' => [
    'manage' => 'icommerce::cartproductoptions.manage resource',
    'index' => 'icommerce::cartproductoptions.list resource',
    'create' => 'icommerce::cartproductoptions.create resource',
    'edit' => 'icommerce::cartproductoptions.edit resource',
    'destroy' => 'icommerce::cartproductoptions.destroy resource',
    'restore' => 'icommerce::cartproductoptions.restore resource',
  ],
  'icommerce.shipping-methods' => [
    'manage' => 'icommerce::shippingmethods.manage resource',
    'index' => 'icommerce::shippingmethods.list resource',
    'create' => 'icommerce::shippingmethods.create resource',
    'edit' => 'icommerce::shippingmethods.edit resource',
    'destroy' => 'icommerce::shippingmethods.destroy resource',
    'restore' => 'icommerce::shippingmethods.restore resource',
  ],
  'icommerce.shippingmethodgeozones' => [
    'manage' => 'icommerce::shippingmethodgeozones.manage resource',
    'index' => 'icommerce::shippingmethodgeozones.list resource',
    'create' => 'icommerce::shippingmethodgeozones.create resource',
    'edit' => 'icommerce::shippingmethodgeozones.edit resource',
    'destroy' => 'icommerce::shippingmethodgeozones.destroy resource',
    'restore' => 'icommerce::shippingmethodgeozones.restore resource',
  ],
  'icommerce.paymentmethodgeozones' => [
    'manage' => 'icommerce::paymentmethodgeozones.manage resource',
    'index' => 'icommerce::paymentmethodgeozones.list resource',
    'create' => 'icommerce::paymentmethodgeozones.create resource',
    'edit' => 'icommerce::paymentmethodgeozones.edit resource',
    'destroy' => 'icommerce::paymentmethodgeozones.destroy resource',
    'restore' => 'icommerce::paymentmethodgeozones.restore resource',
  ],
  'icommerce.productables' => [
    'manage' => 'icommerce::productables.manage resource',
    'index' => 'icommerce::productables.list resource',
    'create' => 'icommerce::productables.create resource',
    'edit' => 'icommerce::productables.edit resource',
    'destroy' => 'icommerce::productables.destroy resource',
    'restore' => 'icommerce::productables.restore resource',
  ],
  'icommerce.couponables' => [
    'manage' => 'icommerce::couponables.manage resource',
    'index' => 'icommerce::couponables.list resource',
    'create' => 'icommerce::couponables.create resource',
    'edit' => 'icommerce::couponables.edit resource',
    'destroy' => 'icommerce::couponables.destroy resource',
    'restore' => 'icommerce::couponables.restore resource',
  ],
  'icommerce.weightclasses' => [
    'manage' => 'icommerce::weightclasses.manage resource',
    'index' => 'icommerce::weightclasses.list resource',
    'create' => 'icommerce::weightclasses.create resource',
    'edit' => 'icommerce::weightclasses.edit resource',
    'destroy' => 'icommerce::weightclasses.destroy resource',
    'restore' => 'icommerce::weightclasses.restore resource',
  ],
  'icommerce.lengthclasses' => [
    'manage' => 'icommerce::lengthclasses.manage resource',
    'index' => 'icommerce::lengthclasses.list resource',
    'create' => 'icommerce::lengthclasses.create resource',
    'edit' => 'icommerce::lengthclasses.edit resource',
    'destroy' => 'icommerce::lengthclasses.destroy resource',
    'restore' => 'icommerce::lengthclasses.restore resource',
  ],
  'icommerce.volumeclasses' => [
    'manage' => 'icommerce::volumeclasses.manage resource',
    'index' => 'icommerce::volumeclasses.list resource',
    'create' => 'icommerce::volumeclasses.create resource',
    'edit' => 'icommerce::volumeclasses.edit resource',
    'destroy' => 'icommerce::volumeclasses.destroy resource',
    'restore' => 'icommerce::volumeclasses.restore resource',
  ],
  'icommerce.quantityclasses' => [
    'manage' => 'icommerce::quantityclasses.manage resource',
    'index' => 'icommerce::quantityclasses.list resource',
    'create' => 'icommerce::quantityclasses.create resource',
    'edit' => 'icommerce::quantityclasses.edit resource',
    'destroy' => 'icommerce::quantityclasses.destroy resource',
    'restore' => 'icommerce::quantityclasses.restore resource',
  ],
  'icommerce.optiontypes' => [
    'manage' => 'icommerce::optiontypes.manage resource',
    'index' => 'icommerce::optiontypes.list resource',
    'create' => 'icommerce::optiontypes.create resource',
    'edit' => 'icommerce::optiontypes.edit resource',
    'destroy' => 'icommerce::optiontypes.destroy resource',
    'restore' => 'icommerce::optiontypes.restore resource',
  ],
  'icommerce.productoptionvalues' => [
    'manage' => 'icommerce::productoptionvalues.manage resource',
    'index' => 'icommerce::productoptionvalues.list resource',
    'create' => 'icommerce::productoptionvalues.create resource',
    'edit' => 'icommerce::productoptionvalues.edit resource',
    'destroy' => 'icommerce::productoptionvalues.destroy resource',
    'restore' => 'icommerce::productoptionvalues.restore resource',
  ],
  'icommerce.warehouses' => [
    'manage' => 'icommerce::warehouses.manage resource',
    'index' => 'icommerce::warehouses.list resource',
    'create' => 'icommerce::warehouses.create resource',
    'edit' => 'icommerce::warehouses.edit resource',
    'destroy' => 'icommerce::warehouses.destroy resource',
    'restore' => 'icommerce::warehouses.restore resource',
  ],
  'icommerce.productwarehouses' => [
    'manage' => 'icommerce::productwarehouses.manage resource',
    'index' => 'icommerce::productwarehouses.list resource',
    'create' => 'icommerce::productwarehouses.create resource',
    'edit' => 'icommerce::productwarehouses.edit resource',
    'destroy' => 'icommerce::productwarehouses.destroy resource',
    'restore' => 'icommerce::productwarehouses.restore resource',
  ],
  'icommerce.productoptionvaluewarehouses' => [
    'manage' => 'icommerce::productoptionvaluewarehouses.manage resource',
    'index' => 'icommerce::productoptionvaluewarehouses.list resource',
    'create' => 'icommerce::productoptionvaluewarehouses.create resource',
    'edit' => 'icommerce::productoptionvaluewarehouses.edit resource',
    'destroy' => 'icommerce::productoptionvaluewarehouses.destroy resource',
    'restore' => 'icommerce::productoptionvaluewarehouses.restore resource',
  ],
// append
];
